version: '3'
services:
  discordbot:
    build: . # Build using Dockerfile in directory
    depends_on:
      - postgres
    environment:
      PORT: 2424
      BOT_TOKEN: '${BOT_TOKEN}' # ${} pulled from .env in same directory
      DATABASE_URL: 'postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}'
      BOT_PREFIX: '${BOT_PREFIX}'
    volumes:
      - .:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    ports:
      - '2424:2424'

  postgres:
    image: postgres:latest
    ports:
      - '35432:5432'
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
